### ISSUE TITLE
There is a conflict here

### ISSUE THREAD

**Issue by ahmedtaa** [clintonjosephs/MovieSpot#35]
Hi @clintonjosephs 

take a look here, please

https://github.com/clintonjosephs/MovieSpot/blob/735545aaa1c2265654412f3fe9b5272c9e778217/src/JS_Modules/Models/InvolvementService.js#L3

sendComment function here accept only 3 args

https://github.com/clintonjosephs/MovieSpot/blob/735545aaa1c2265654412f3fe9b5272c9e778217/src/JS_Modules/Controllers/CommentManager.js#L15

and here it is called with 4 args

**Comment by ahmedtaa** [comment]
Hi @clintonjosephs 

I removed the 4th argument `commentForm` and rearrange the code and all working fine 

Please double-check and confirm changes

**Comment by clintonjosephs** [comment]
Oh 😊, I see how you modified it now! Clever job.

This is a better approach than what I had in mind initially. Great Job 👍
